spring:
  data:
    mongodb:
      database: keeper
      port: 27017
      host: localhost
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server:
  port: 8080
filer:
  host: http://examp.le
  port: 8088